<a href="https://colab.research.google.com/github/mradi004/data_science/blob/main/group_by_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
delivery=pd.read_csv('/content/deliveries.csv')

In [5]:
imdb=pd.read_csv('/content/imdb-top-1000.csv')

In [6]:
imdb

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [7]:
imdb.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [8]:
genre=imdb.groupby('Genre')

In [9]:
genre.count()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,172,172,172,172,172,172,172,143
Adventure,72,72,72,72,72,72,72,72,64
Animation,82,82,82,82,82,82,82,82,75
Biography,88,88,88,88,88,88,88,88,79
Comedy,155,155,155,155,155,155,155,155,125
Crime,107,107,107,107,107,107,107,107,87
Drama,289,289,289,289,289,289,289,289,241
Family,2,2,2,2,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,11,11,11,11,11,11,11
Mystery,12,12,12,12,12,12,12,12,8
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,4,4,4,4,4

In [10]:
imdb

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [11]:
imdb.groupby('Genre').sum()['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [12]:
imdb.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [13]:
imdb.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(3)

Genre
Western    8.350000
Crime      8.016822
Fantasy    8.000000
Name: IMDB_Rating, dtype: float64

In [14]:
imdb.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(3)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
Name: No_of_Votes, dtype: int64

In [15]:
m=imdb.groupby('Genre')['IMDB_Rating'].max().sort_values(ascending=False).head(3)

In [16]:
imdb['Star1'].value_counts()

Star1
Tom Hanks              12
Robert De Niro         11
Al Pacino              10
Clint Eastwood         10
Humphrey Bogart         9
                       ..
Junko Iwao              1
Fernanda Montenegro     1
Eli Marienthal          1
Til Schweiger           1
Alan Mak                1
Name: count, Length: 660, dtype: int64

In [17]:
imdb.groupby('Star1')['Series_Title'].count().sort_values(ascending=False).head(3)

Star1
Tom Hanks         12
Robert De Niro    11
Clint Eastwood    10
Name: Series_Title, dtype: int64

In [18]:
len(imdb.groupby('Genre'))

14

In [19]:
imdb.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [20]:
genres=imdb.groupby('Genre')

In [21]:
genres.first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [22]:
genres.nth(6)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [23]:
#get_group
genres.get_group('Horror')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [24]:
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [25]:
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [26]:
#Aggregate Functions

In [27]:
genres.agg({
    'Runtime':'mean',
    'IMDB_Rating':"mean",
    'No_of_Votes':'mean',
    'Gross':'sum',
    'Metascore':'min'
})

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  3.263226e+10       33.0
Adventure  134.111111     7.937500  313557.819444  9.496922e+09       41.0
Animation   99.585366     7.930488  268032.073171  1.463147e+10       61.0
Biography  136.022727     7.938636  272805.045455  8.276358e+09       48.0
Comedy     112.129032     7.901290  178195.658065  1.566387e+10       45.0
Crime      126.392523     8.016822  313398.271028  8.452632e+09       47.0
Drama      124.737024     7.957439  212343.612457  3.540997e+10       28.0
Family     107.500000     7.800000  275610.500000  4.391106e+08       67.0
Fantasy     85.000000     8.000000   73111.000000  7.827267e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  1.259105e+08       94.0
Horror     102.090909     7.909091  340232.363636  1.034649e+09       46.0
Mystery    119.083333     7.975000  350250.333333  1.256417e+09       52.0
Thriller   108.000000     7.800000   27733.000000  1.755074e+07       81.0
Western    148.250000     8.350000  322416.250000  5.822151e+07       69.0

In [28]:
genres.agg(['min','max','sum'])

                              Series_Title  \
                                       min
Genre
Action                                 300
Adventure            2001: A Space Odyssey
Animation                            Akira
Biography                 12 Years a Slave
Comedy                (500) Days of Summer
Crime                         12 Angry Men
Drama                                 1917
Family          E.T. the Extra-Terrestrial
Fantasy       Das Cabinet des Dr. Caligari
Film-Noir                Shadow of a Doubt
Horror                               Alien
Mystery                          Dark City
Thriller                   Wait Until Dark
Western    Il buono, il brutto, il cattivo

                                                \
                                           max
Genre
Action                                 Yôjinbô
Adventure                           Zombieland
Animation          Ôkami kodomo no Ame to Yuki
Biography                              Zerkalo
Comedy                Zindagi Na Milegi Dobara
Crime                        À bout de souffle
Drama                                Zwartboek
Family     Willy Wonka & the Chocolate Factory
Fantasy                              Nosferatu
Film-Noir                        The Third Man
Horror                               The Thing
Mystery                                Vertigo
Thriller                       Wait Until Dark
Western                 The Outlaw Josey Wales

                                                             Released_Year  \
                                                         sum           min
Genre
Action     The Dark KnightThe Lord of the Rings: The Retu...          1924
Adventure  InterstellarBack to the FutureInglourious Bast...          1925
Animation  Sen to Chihiro no kamikakushiThe Lion KingHota...          1940
Biography  Schindler's ListGoodfellasHamiltonThe Intoucha...          1928
Comedy     GisaengchungLa vita è bellaModern TimesCity Li...          1921
Crime      The GodfatherThe Godfather: Part II12 Angry Me...          1931
Drama      The Shawshank RedemptionFight ClubForrest Gump...          1925
Family     E.T. the Extra-TerrestrialWilly Wonka & the Ch...          1971
Fantasy                Das Cabinet des Dr. CaligariNosferatu          1920
Film-Noir   The Third ManThe Maltese FalconShadow of a Doubt          1941
Horror     PsychoAlienThe ThingThe ExorcistNight of the L...          1933
Mystery    MementoRear WindowVertigoShutter IslandKahaani...          1938
Thriller                                     Wait Until Dark          1967
Western    Il buono, il brutto, il cattivoOnce Upon a Tim...          1965

                                                                   Runtime  \
            max                                                sum     min
Genre
Action     2019  2008200320102001200219991980197719621954200019...      45
Adventure    PG  2014198520091981196819621959201319751963194819...      88
Animation  2020  2001199419882016201820172008199719952019200920...      71
Biography  2020  1993199020202011200220171995198420182013201320...      93
Comedy     2020  2019199719361931200919641940200120001973196019...      68
Crime      2019  1972197419571994200219991995199120192006199519...      80
Drama      2020  1994199919941975202019981946201420061998198819...      64
Family     1982                                           19821971     100
Fantasy    1922                                           19201922      76
Film-Noir  1949                                       194919411943     100
Horror     2017       19601979198219731968196120171978193320042001      71
Mystery    2012   200019541958201020121995197219381988201219981997      96
Thriller   1967                                               1967     108
Western    1976                                   1966196819651976     132

                      IMDB_Rating  ...  \
           max    sum         min  ...
Genre                              ...
Action     321  22196         7.6  ...
Adventure  228   9656         7.6  ...
Animation  137   8166         7.6  ...
Biography  209  11970         7.6  ...
Comedy     188  17380         7.6  ...
Crime      229  13524         7.6  ...
Drama      242  36049         7.6  ...
Family     115    215         7.8  ...
Fantasy     94    170         7.9  ...
Film-Noir  108    312         7.8  ...
Horror     122   1123         7.6  ...
Mystery    138   1429         7.6  ...
Thriller   108    108         7.8  ...
Western    165    593         7.8  ...

                                                       Star1 No_of_Votes  \
                                                         sum         min
Genre
Action     Christian BaleElijah WoodLeonardo DiCaprioElij...       25312
Adventure  Matthew McConaugheyMichael J. FoxBrad PittJürg...       29999
Animation  Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...       25229
Biography  Liam NeesonRobert De NiroLin-Manuel MirandaÉri...       27254
Comedy     Kang-ho SongRoberto BenigniCharles ChaplinChar...       26337
Crime      Marlon BrandoAl PacinoHenry FondaJohn Travolta...       27712
Drama      Tim RobbinsBrad PittTom HanksJack NicholsonSur...       25088
Family                               Henry ThomasGene Wilder      178731
Fantasy                             Werner KraussMax Schreck       57428
Film-Noir           Orson WellesHumphrey BogartTeresa Wright       59556
Horror     Anthony PerkinsSigourney WeaverKurt RussellEll...       27007
Mystery    Guy PearceJames StewartJames StewartLeonardo D...       33982
Thriller                                      Audrey Hepburn       27733
Western    Clint EastwoodHenry FondaClint EastwoodClint E...       65659

                                    Gross                             \
               max       sum          min          max           sum
Genre
Action     2303232  72282412       3296.0  936662225.0  3.263226e+10
Adventure  1512360  22576163      61001.0  874211619.0  9.496922e+09
Animation   999790  21978630     128985.0  873839108.0  1.463147e+10
Biography  1213505  24006844      21877.0  753585104.0  8.276358e+09
Comedy      939631  27620327       1305.0  886752933.0  1.566387e+10
Crime      1826188  33533615       6013.0  790482117.0  8.452632e+09
Drama      2343110  61367304       3600.0  924558264.0  3.540997e+10
Family      372490    551221    4000000.0  435110554.0  4.391106e+08
Fantasy      88794    146222  337574718.0  445151978.0  7.827267e+08
Film-Noir   158731    367215     449191.0  123353292.0  1.259105e+08
Horror      787806   3742556      89029.0  298791505.0  1.034649e+09
Mystery    1129894   4203004    1035953.0  474203697.0  1.256417e+09
Thriller     27733     27733   17550741.0   17550741.0  1.755074e+07
Western     688390   1289665    5321508.0   31800000.0  5.822151e+07

          Metascore
                min    max      sum
Genre
Action         33.0   98.0  10499.0
Adventure      41.0  100.0   5020.0
Animation      61.0   96.0   6082.0
Biography      48.0   97.0   6023.0
Comedy         45.0   99.0   9840.0
Crime          47.0  100.0   6706.0
Drama          28.0  100.0  19208.0
Family         67.0   91.0    158.0
Fantasy         NaN    NaN      0.0
Film-Noir      94.0   97.0    287.0
Horror         46.0   97.0    880.0
Mystery        52.0  100.0    633.0
Thriller       81.0   81.0     81.0
Western        69.0   90.0    313.0

[14 rows x 27 columns]

In [29]:
genres.agg({
    'Runtime':['mean','max'],
    'IMDB_Rating':"mean",
    'No_of_Votes':'mean',
    'Gross':['sum','max'],
    'Metascore':'min'
})

              Runtime      IMDB_Rating    No_of_Votes         Gross  \
                 mean  max        mean           mean           sum
Genre
Action     129.046512  321    7.949419  420246.581395  3.263226e+10
Adventure  134.111111  228    7.937500  313557.819444  9.496922e+09
Animation   99.585366  137    7.930488  268032.073171  1.463147e+10
Biography  136.022727  209    7.938636  272805.045455  8.276358e+09
Comedy     112.129032  188    7.901290  178195.658065  1.566387e+10
Crime      126.392523  229    8.016822  313398.271028  8.452632e+09
Drama      124.737024  242    7.957439  212343.612457  3.540997e+10
Family     107.500000  115    7.800000  275610.500000  4.391106e+08
Fantasy     85.000000   94    8.000000   73111.000000  7.827267e+08
Film-Noir  104.000000  108    7.966667  122405.000000  1.259105e+08
Horror     102.090909  122    7.909091  340232.363636  1.034649e+09
Mystery    119.083333  138    7.975000  350250.333333  1.256417e+09
Thriller   108.000000  108    7.800000   27733.000000  1.755074e+07
Western    148.250000  165    8.350000  322416.250000  5.822151e+07

                       Metascore
                   max       min
Genre
Action     936662225.0      33.0
Adventure  874211619.0      41.0
Animation  873839108.0      61.0
Biography  753585104.0      48.0
Comedy     886752933.0      45.0
Crime      790482117.0      47.0
Drama      924558264.0      28.0
Family     435110554.0      67.0
Fantasy    445151978.0       NaN
Film-Noir  123353292.0      94.0
Horror     298791505.0      46.0
Mystery    474203697.0      52.0
Thriller    17550741.0      81.0
Western     31800000.0      69.0

In [30]:
#looping on groups
df=pd.DataFrame(columns=imdb.columns)
for group,data in genres:
  # Use pd.concat instead of append
  df=pd.concat([df, data[data['IMDB_Rating']==data['IMDB_Rating'].max()]])

/tmp/ipython-input-30-2952059609.py:5: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df=pd.concat([df, data[data['IMDB_Rating']==data['IMDB_Rating'].max()]])

In [31]:
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [32]:
#apply function
genres.apply(min)

/tmp/ipython-input-32-1477424214.py:2: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  genres.apply(min)
/tmp/ipython-input-32-1477424214.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(min)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN
Crime,12 Angry Men,1931,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,NaN
Drama,1917,1925,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,NaN
Family,E.T. the Extra-Terrestrial,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,NaN
Thriller,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [37]:
#find the movies starting with A for each group
def foo(group):
  return group['Series_Title'].str.startswith('A').sum()

In [38]:
genres.apply(foo)

/tmp/ipython-input-38-2904676014.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(foo)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [39]:
#find ranking of each movie in the group according to imdb rating
def rank(group):
  group['ranking']=group['IMDB_Rating'].rank(ascending=False)
  return group

In [40]:
genres.apply(rank)

/tmp/ipython-input-40-2303385112.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(rank)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  ranking
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0      1.0
         5          Elijah Wood      1642758  377845905.0       94.0      2.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0      3.5
         10         Elijah Wood      1661481  315544750.0       92.0      3.5
         13         Elijah Wood      1485555  342551365.0       87.0      6.0
...                         ...          ...          ...        ...      ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0      1.0
Western  12      Clint Eastwood       688390    6100000.0       90.0      1.0
         48         Henry Fonda       302844    5321508.0       80.0      2.0
         115     Clint Eastwood       232772   15000000.0       74.0      3.0
         691     Clint Eastwood        65659   31800000.0       69.0      4.0

[1000 rows x 11 columns]

In [41]:
#noramlised rating
def too(group):
  group['normalise_rating']=(group['IMDB_Rating']-group['IMDB_Rating'].min())/(group['IMDB_Rating'].max()-group['IMDB_Rating'].min())
  return group

In [42]:
genres.apply(too)

/tmp/ipython-input-42-2110899174.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(too)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              normalise_rating
Genre
Action   2            1.000000
         5            0.928571
         8            0.857143
         10           0.857143
         13           0.785714
...                        ...
Thriller 700               NaN
Western  12           1.000000
         48           0.700000
         115          0.500000
         691          0.000000

[1000 rows x 11 columns]

In [49]:
#GROUPBY FOR multiple column
duo=imdb.groupby(['Genre','Director'])

In [50]:
duo.size()

Genre     Director
Action    Abhishek Chaubey         1
          Aditya Dhar              1
          Akira Kurosawa           4
          Alejandro G. Iñárritu    1
          Andrew Davis             1
                                  ..
Mystery   Sujoy Ghosh              1
          Terry Gilliam            1
Thriller  Terence Young            1
Western   Clint Eastwood           1
          Sergio Leone             3
Length: 749, dtype: int64

In [52]:
duo['Gross'].sum().sort_values(ascending=False)

Genre      Director
Animation  Hayao Miyazaki            2.447325e+09
Action     Anthony Russo             2.205039e+09
           Christopher Nolan         1.670799e+09
Drama      Ingmar Bergman            1.654929e+09
           Michelangelo Antonioni    1.505392e+09
                                         ...
           Vikramaditya Motwane      7.461000e+03
Action     Jeong-beom Lee            6.460000e+03
Drama      Jaco Van Dormael          3.600000e+03
Action     Thomas Jahn               3.296000e+03
Comedy     Anders Thomas Jensen      1.305000e+03
Name: Gross, Length: 749, dtype: float64

In [56]:
dem=imdb.groupby(['Star1','Genre'])['Metascore'].mean().reset_index().sort_values('Metascore',ascending=False)

In [57]:
dem

                Star1      Genre  Metascore
606     Peter O'Toole  Adventure      100.0
590      Orson Welles      Drama      100.0
77        Bertil Guve      Drama      100.0
230    Ellar Coltrane      Drama      100.0
329   Humphrey Bogart      Drama      100.0
..                ...        ...        ...
807    William Holden      Drama        NaN
812           Won Bin     Action        NaN
815              Yash     Action        NaN
826    Çetin Tekindor      Drama        NaN
828  Ömer Faruk Sorak     Comedy        NaN

[829 rows x 3 columns]

In [58]:
ipl=pd.read_csv('/content/deliveries.csv')

In [61]:
ipl.head(1)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [65]:
dem2=ipl.groupby(['batsman'])['batsman_runs'].sum().sort_values(ascending=False)

In [66]:
dem2

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
                  ...
S Lamichhane         0
Sunny Gupta          0
Abdur Razzak         0
U Kaul               0
V Pratap Singh       0
Name: batsman_runs, Length: 516, dtype: int64

In [68]:
dem4=ipl[ipl['batsman_runs']==6]

In [69]:
dem4.groupby('batsman')['batsman'].count().sort_values(ascending=False)

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
                 ...
AN Ahmed            1
AD Mascarenhas      1
TA Boult            1
T Kohli             1
TS Mills            1
Name: batsman, Length: 336, dtype: int64

In [75]:
dem5=ipl[ipl['over']>15]

In [76]:
dem5

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
93,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,1,MC Henriques,Yuvraj Singh,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
94,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,2,MC Henriques,Yuvraj Singh,YS Chahal,0,...,0,0,0,0,0,0,0,MC Henriques,caught,Sachin Baby
95,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,3,Yuvraj Singh,DJ Hooda,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
96,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,4,DJ Hooda,Yuvraj Singh,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
97,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,5,Yuvraj Singh,DJ Hooda,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [80]:
dem6=dem5[(dem5['batsman_runs']==4)|(dem5['batsman_runs']==6)]

In [81]:
dem6

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
101,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,17,3,Yuvraj Singh,DJ Hooda,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
105,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,18,1,DJ Hooda,Yuvraj Singh,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
109,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,18,5,Yuvraj Singh,DJ Hooda,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
114,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,19,2,Yuvraj Singh,DJ Hooda,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
115,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,19,3,Yuvraj Singh,DJ Hooda,TS Mills,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179052,11415,2,Chennai Super Kings,Mumbai Indians,16,5,SR Watson,DJ Bravo,SL Malinga,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
179061,11415,2,Chennai Super Kings,Mumbai Indians,18,2,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179062,11415,2,Chennai Super Kings,Mumbai Indians,18,3,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179063,11415,2,Chennai Super Kings,Mumbai Indians,18,4,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179071,11415,2,Chennai Super Kings,Mumbai Indians,19,6,RA Jadeja,SR Watson,JJ Bumrah,0,...,4,0,0,0,4,4,8,NaN,NaN,NaN

In [82]:
dem6.groupby('batsman')['batsman'].count().sort_values(ascending=False)

batsman
MS Dhoni          340
RG Sharma         208
AB de Villiers    208
KA Pollard        206
V Kohli           160
                 ...
AR Bawne            1
TS Mills            1
TA Boult            1
T Taibu             1
T Curran            1
Name: batsman, Length: 360, dtype: int64

In [83]:
tempdf=ipl[ipl['batsman']=='V Kohli']

In [86]:
tempdf.groupby('bowling_team')['batsman_runs'].sum()

bowling_team
Chennai Super Kings        749
Deccan Chargers            306
Delhi Capitals              66
Delhi Daredevils           763
Gujarat Lions              283
Kings XI Punjab            636
Kochi Tuskers Kerala        50
Kolkata Knight Riders      675
Mumbai Indians             628
Pune Warriors              128
Rajasthan Royals           370
Rising Pune Supergiant      83
Rising Pune Supergiants    188
Sunrisers Hyderabad        509
Name: batsman_runs, dtype: int64

In [91]:
tempdff=ipl[ipl['batsman']=='V Kohli']
tempdff.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False)

match_id
626      113
620      109
611      108
595      100
11326    100
        ...
27         0
488        0
481        0
462        0
633        0
Name: batsman_runs, Length: 169, dtype: int64

In [94]:
def high(batsman):
  tempdff=ipl[ipl['batsman']==batsman]
  return tempdff.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1)

In [95]:
high('CH Gayle')

match_id
411    175
Name: batsman_runs, dtype: int64