<a href="https://colab.research.google.com/github/mradi004/data_science/blob/main/pandas_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

from matplotlib import pyplot as plt
_df_0['PassengerId'].plot(kind='hist', bins=20, title='PassengerId')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Survived'].plot(kind='hist', bins=20, title='Survived')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Pclass'].plot(kind='hist', bins=20, title='Pclass')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='PassengerId', y='Survived', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='Survived', y='Pclass', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Pclass', y='Age', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Age', y='SibSp', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8['PassengerId'].plot(kind='line', figsize=(8, 4), title='PassengerId')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Survived'].plot(kind='line', figsize=(8, 4), title='Survived')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Pclass'].plot(kind='line', figsize=(8, 4), title='Pclass')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_11['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df[['Name','Sex','Ticket','Cabin','Embarked']]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [ ]:
df.dtypes=='object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [ ]:
df.dtypes[df.dtypes =='object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [ ]:
df[df.dtypes[df.dtypes=='object'].index].describe()

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

In [ ]:
df[df.dtypes[df.dtypes=='float'].index]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [ ]:
df[df.dtypes[df.dtypes=='int64'].index]

     PassengerId  Survived  Pclass  SibSp  Parch
0              1         0       3      1      0
1              2         1       1      1      0
2              3         1       3      0      0
3              4         1       1      1      0
4              5         0       3      0      0
..           ...       ...     ...    ...    ...
886          887         0       2      0      0
887          888         1       1      0      0
888          889         0       3      1      2
889          890         1       1      0      0
890          891         0       3      0      0

[891 rows x 5 columns]

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df[['Ticket']][4:11]

     Ticket
4    373450
5    330877
6     17463
7    349909
8    347742
9    237736
10  PP 9549

In [ ]:
df['new_col']=0

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [ ]:
df["new_col_1"]=df["PassengerId"]+df['Pclass']

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,new_col_1
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,4
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,3
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,6
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,5
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0,889
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,889
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0,892
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,891
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0,894

In [ ]:
pd.Categorical(df['Pclass']) #shows th unique data and the amount of data in it.

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [ ]:
pd.Categorical(df['Survived'])

[0, 1, 1, 1, 0, ..., 0, 1, 0, 1, 0]
Length: 891
Categories (2, int64): [0, 1]

In [ ]:
pd.Categorical(df['Cabin'])

[NaN, 'C85', NaN, 'C123', NaN, ..., NaN, 'B42', NaN, 'C148', NaN]
Length: 891
Categories (147, object): ['A10', 'A14', 'A16', 'A19', ..., 'F38', 'F4', 'G6', 'T']

In [ ]:
df[df['Age']>18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,new_col_1
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,4
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,3
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,6
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,5
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,0,889
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0,889
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,889
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,891
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0,894

In [ ]:
df[df['Fare']>32]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,new_col_1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,3
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,5
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,0,8
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,0,25
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,0,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S,0,858
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,0,867
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S,0,869
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,0,873
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,0,881

In [ ]:
df[df['Fare']==0]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,new_col_1
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0,NaN,S,0,183
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S,0,265
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0,NaN,S,0,275
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0,NaN,S,0,280
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0,NaN,S,0,306
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0,NaN,S,0,416
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0,NaN,S,0,469
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S,0,484
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0,NaN,S,0,601
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0,NaN,S,0,635
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0,NaN,S,0,677
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0,NaN,S,0,735
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0,A36,S,0,808
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S,0,817
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0,NaN,S,0,824

In [ ]:
df[df['Sex']=='male']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,new_col_1
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,4
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,8
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,0,9
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,0,8
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,0,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,0,886
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,0,888
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0,889
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,891
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0,894

In [ ]:
df[df['Sex']=='female']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,new_col_1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,3
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,6
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,5
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,0,12
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,0,883
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S,0,886
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,0,889
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,889
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0,892

In [ ]:
df[(df['Sex']=='female') & (df['Fare']>32)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,new_col_1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,3
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,5
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C,0,33
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C,0,46
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,0,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S,0,855
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S,0,858
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,0,867
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,0,873
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,0,881

In [ ]:
df[(df['Sex']=='male')&(df['Fare']>32)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,new_col_1
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,0,8
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,0,25
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,0,29
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C,0,36
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S,0,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
827,828,1,2,"Mallet, Master. Andre",male,1.0,0,2,S.C./PARIS 2079,37.0042,NaN,C,0,830
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S,0,842
846,847,0,3,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S,0,850
848,849,0,2,"Harper, Rev. John",male,28.0,0,1,248727,33.0000,NaN,S,0,851
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S,0,869

In [ ]:
df[df['Fare']==max(df['Fare'])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
#COLLECTING ROWS FROM DATAFRAMES

In [ ]:
df[0::2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
df[['PassengerId','Survived','Pclass']][0:2]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1

In [ ]:
df.iloc[0:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
df.iloc[0:2]['Sex','Fare','Name']

KeyError: ('Sex', 'Fare', 'Name')

In [ ]:
df.loc[0:2]['Sex','Fare','Name']

KeyError: ('Sex', 'Fare', 'Name')

In [ ]:
df.loc[0:2,['Sex','Fare','Name']]

      Sex     Fare                                               Name
0    male   7.2500                            Braund, Mr. Owen Harris
1  female  71.2833  Cumings, Mrs. John Bradley (Florence Briggs Th...
2  female   7.9250                             Heikkinen, Miss. Laina

In [ ]:
df.iloc[0:2,[0,1,2]]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1

#pandas 3rd lecture

In [ ]:
s=df['Name'][0:11]

In [ ]:
s

0                               Braund, Mr. Owen Harris
1     Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr. William Henry
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
Name: Name, dtype: object

In [ ]:
l=['a','b','c','d','e','f','g','h','i','j','k']

In [ ]:
s1=pd.Series(list(s),index=l) #naming the index

In [ ]:
s1

a                              Braund, Mr. Owen Harris
b    Cumings, Mrs. John Bradley (Florence Briggs Th...
c                               Heikkinen, Miss. Laina
d         Futrelle, Mrs. Jacques Heath (Lily May Peel)
e                             Allen, Mr. William Henry
f                                     Moran, Mr. James
g                              McCarthy, Mr. Timothy J
h                       Palsson, Master. Gosta Leonard
i    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
j                  Nasser, Mrs. Nicholas (Adele Achem)
k                      Sandstrom, Miss. Marguerite Rut
dtype: object

In [ ]:
s1['a']

'Braund, Mr. Owen Harris'

In [ ]:
s2 = pd.concat([s1, s])

In [ ]:
s2

a                               Braund, Mr. Owen Harris
b     Cumings, Mrs. John Bradley (Florence Briggs Th...
c                                Heikkinen, Miss. Laina
d          Futrelle, Mrs. Jacques Heath (Lily May Peel)
e                              Allen, Mr. William Henry
f                                      Moran, Mr. James
g                               McCarthy, Mr. Timothy J
h                        Palsson, Master. Gosta Leonard
i     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
j                   Nasser, Mrs. Nicholas (Adele Achem)
k                       Sandstrom, Miss. Marguerite Rut
0                               Braund, Mr. Owen Harris
1     Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr. William Henry
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
dtype: object

In [ ]:
s3=pd.Series([23,45,65,32,43],index=[1,2,3,4,5])

In [ ]:
s4=pd.Series([65,45,65,76,87],index=[1,7,8,9,10])

In [ ]:
s5=pd.concat([s3,s4])

In [ ]:
s5

1     23
2     45
3     65
4     32
5     43
1     65
7     45
8     65
9     76
10    87
dtype: int64

In [ ]:
s5[1]

1    23
1    65
dtype: int64

In [ ]:
s3*s4

1     1495.0
2        NaN
3        NaN
4        NaN
5        NaN
7        NaN
8        NaN
9        NaN
10       NaN
dtype: float64

#pandas 4

In [ ]:
#drop command

In [ ]:
df2=df.drop('PassengerId',axis=1)

In [ ]:
df2

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
df2.drop(3,inplace=True)

In [ ]:
df2

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
df2.set_index('Name',inplace=True)

In [ ]:
df2

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
Name,,,,,,,,,,,,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
df2.reset_index(inplace=True)

/tmp/ipython-input-103-798617561.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2.reset_index(inplace=True)

In [ ]:
d={
    'key1':[3,4,5,6,7],
    'key2':[5,6,7,8,9],
    'key3':[4,5,6,7,8]
}

In [ ]:
pd.DataFrame(d)

   key1  key2  key3
0     3     5     4
1     4     6     5
2     5     7     6
3     6     8     7
4     7     9     8

In [ ]:
bs=pd.read_csv("customers-1000.csv")

In [ ]:
bs

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/

In [ ]:
bs.dropna()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/

In [ ]:
df2.dropna()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
5,"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
9,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
10,"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
20,"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,1,female,47.0,1,1,11751,52.5542,D35,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
871,"Carlsson, Mr. Frans Olof",0,1,male,33.0,0,0,695,5.0000,B51 B53 B55,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
878,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,1,female,56.0,0,1,11767,83.1583,C50,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
df.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
df.dropna(axis=1)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,new_col,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500,0,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833,0,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250,0,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000,0,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500,0,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000,0,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000,0,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500,0,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000,0,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500,0,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
bs.dropna(axis=1)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/

In [ ]:
#group by function

In [ ]:
g=df.groupby('Survived')

In [ ]:
g

In [ ]:
g.sum()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
Survived,,,,,,,,,,,,,,,,,,,,,
0,245412,1390,"Braund, Mr. Owen HarrisAllen, Mr. William Henr...",malemalemalemalemalemalemalefemalemalefemalema...,12985.50,304,181,A/5 2117137345033087717463349909A/5. 215134708...,12142.7199,E46C23 C25 C27B30C83F G73E31A5D26C110B58 B60D2...,...,281268.7308,281268.7308,281268.7308,281268.7308,281268.7308,281268.7308,281268.7308,281268.7308,281268.7308,281268.7308
1,151974,667,"Cumings, Mrs. John Bradley (Florence Briggs Th...",femalefemalefemalefemalefemalefemalefemalefema...,8219.67,162,159,PC 17599STON/O2. 3101282113803347742237736PP 9...,16551.2294,C85C123G6C103D56A6B78D33C52B28F33C23 C25 C27D1...,...,175216.5864,175216.5864,175216.5864,175216.5864,175216.5864,175216.5864,175216.5864,175216.5864,175216.5864,175216.5864

In [ ]:
g1=df.groupby('Pclass')

In [ ]:
g1.sum()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
Pclass,,,,,,,,,,,,,,,,,,,,,
1,99705,136,"Cumings, Mrs. John Bradley (Florence Briggs Th...",femalefemalemalefemalemalemalemalefemalemalema...,7111.42,90,77,PC 175991138031746311378311378819950PC 17601PC...,18177.4125,C85C123E46C103A6C23 C25 C27B78D33B30C52B28C83C...,...,110663.1072,110663.1072,110663.1072,110663.1072,110663.1072,110663.1072,110663.1072,110663.1072,110663.1072,110663.1072
2,82056,87,"Nasser, Mrs. Nicholas (Adele Achem)Hewlett, Mr...",femalefemalemalemalemalemalefemalefemalefemale...,5168.83,74,70,237736248706244373239865248698C.A. 2457911668S...,3801.8417,D56F33E101F2F4F2DE101DF2F33DF33F4E101E77,...,94268.5728,94268.5728,94268.5728,94268.5728,94268.5728,94268.5728,94268.5728,94268.5728,94268.5728,94268.5728
3,215625,119,"Braund, Mr. Owen HarrisHeikkinen, Miss. LainaA...",malefemalemalemalemalefemalefemalemalemalefema...,8924.92,302,193,A/5 21171STON/O2. 3101282373450330877349909347...,6714.6951,G6F G73F E69G6G6G6E10F G63F G73E121F38E121,...,251553.6372,251553.6372,251553.6372,251553.6372,251553.6372,251553.6372,251553.6372,251553.6372,251553.6372,251553.6372

In [ ]:
g1.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
g1.mean(numeric_only=True)

,PassengerId,Survived,Age,SibSp,Parch,Fare,new_col,new_col_1,7.25,71.2833,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
Pclass,,,,,,,,,,,,,,,,,,,,,
1,461.597222,0.629630,38.233441,0.416667,0.356481,84.154687,0.0,462.597222,512.3292,512.3292,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
2,445.956522,0.472826,29.877630,0.402174,0.380435,20.662183,0.0,447.956522,512.3292,512.3292,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
3,439.154786,0.242363,25.140620,0.615071,0.393075,13.675550,0.0,442.154786,512.3292,512.3292,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
g1.describe()

       PassengerId                                                             \
             count        mean         std   min     25%    50%    75%    max
Pclass
1            216.0  461.597222  246.737616   2.0  270.75  472.0  670.5  890.0
2            184.0  445.956522  250.852161  10.0  234.50  435.5  668.0  887.0
3            491.0  439.154786  264.441453   1.0  200.00  432.0  666.5  891.0

       Survived            ...    9.8458           10.5167            \
          count      mean  ...       75%       max   count      mean
Pclass                     ...
1         216.0  0.629630  ...  512.3292  512.3292   216.0  512.3292
2         184.0  0.472826  ...  512.3292  512.3292   184.0  512.3292
3         491.0  0.242363  ...  512.3292  512.3292   491.0  512.3292


                 std       min       25%       50%       75%       max
Pclass
1       2.962724e-12  512.3292  512.3292  512.3292  512.3292  512.3292
2       2.165944e-12  512.3292  512.3292  512.3292  512.3292  512.3292
3       1.707042e-12  512.3292  512.3292  512.3292  512.3292  512.3292

[3 rows x 2048 columns]

In [ ]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,881,882,883,884,885,886,887,888,889,890
PassengerId,1,2,3,4,5,6,7,8,9,10,...,882,883,884,885,886,887,888,889,890,891
Survived,0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,1,0
Pclass,3,1,3,1,3,3,1,3,3,2,...,3,3,2,3,3,2,1,3,1,3
Name,"Braund, Mr. Owen Harris","Cumings, Mrs. John Bradley (Florence Briggs Th...","Heikkinen, Miss. Laina","Futrelle, Mrs. Jacques Heath (Lily May Peel)","Allen, Mr. William Henry","Moran, Mr. James","McCarthy, Mr. Timothy J","Palsson, Master. Gosta Leonard","Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)","Nasser, Mrs. Nicholas (Adele Achem)",...,"Markun, Mr. Johann","Dahlberg, Miss. Gerda Ulrika","Banfield, Mr. Frederick James","Sutehall, Mr. Henry Jr","Rice, Mrs. William (Margaret Norton)","Montvila, Rev. Juozas","Graham, Miss. Margaret Edith","Johnston, Miss. Catherine Helen ""Carrie""","Behr, Mr. Karl Howell","Dooley, Mr. Patrick"
Sex,male,female,female,female,male,male,male,male,female,female,...,male,female,male,male,female,male,female,female,male,male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13.8583,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
50.4958,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
5.0,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
9.8458,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
10.5167,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
g5=df.groupby('Sex')['Survived'].sum()

In [ ]:
g5

Sex
female    233
male      109
Name: Survived, dtype: int64

In [ ]:
g5.transpose()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,...,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292,512.3292

In [ ]:
df.columns

Index(['PassengerId',    'Survived',      'Pclass',        'Name',
               'Sex',         'Age',       'SibSp',       'Parch',
            'Ticket',        'Fare',
       ...
                6.95,           8.3,        6.4375,          39.4,
             14.1083,       13.8583,       50.4958,           5.0,
              9.8458,       10.5167],
      dtype='object', length=262)

In [ ]:
adi=df[['PassengerId',    'Survived',      'Pclass',        'Name','Sex', 'Age',       'SibSp',       'Parch','Ticket',        'Fare']]

In [ ]:
adi

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500

In [ ]:
ishu=adi[['Name','Survived','Pclass']][0:5]

In [ ]:
ishu

                                                Name  Survived  Pclass
0                            Braund, Mr. Owen Harris         0       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
2                             Heikkinen, Miss. Laina         1       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1       1
4                           Allen, Mr. William Henry         0       3

In [ ]:
ishu2=adi[['Name','Survived','Pclass']][5:10]

#concatenation operation

In [ ]:
ishu3=pd.concat([ishu,ishu2])

In [ ]:
ishu3

                                                Name  Survived  Pclass
0                            Braund, Mr. Owen Harris         0       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
2                             Heikkinen, Miss. Laina         1       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1       1
4                           Allen, Mr. William Henry         0       3
5                                   Moran, Mr. James         0       3
6                            McCarthy, Mr. Timothy J         0       1
7                     Palsson, Master. Gosta Leonard         0       3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1       3
9                Nasser, Mrs. Nicholas (Adele Achem)         1       2

In [ ]:
ishu4=pd.concat([ishu,ishu2],axis=1)

In [ ]:
ishu4

,Name,Survived,Pclass,Name,Survived,Pclass
0,"Braund, Mr. Owen Harris",0.0,3.0,NaN,NaN,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1.0,1.0,NaN,NaN,NaN
2,"Heikkinen, Miss. Laina",1.0,3.0,NaN,NaN,NaN
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1.0,1.0,NaN,NaN,NaN
4,"Allen, Mr. William Henry",0.0,3.0,NaN,NaN,NaN
5,NaN,NaN,NaN,"Moran, Mr. James",0.0,3.0
6,NaN,NaN,NaN,"McCarthy, Mr. Timothy J",0.0,1.0
7,NaN,NaN,NaN,"Palsson, Master. Gosta Leonard",0.0,3.0
8,NaN,NaN,NaN,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1.0,3.0
9,NaN,NaN,NaN,"Nasser, Mrs. Nicholas (Adele Achem)",1.0,2.0

In [ ]:
ishu4.fillna("aditya")

,Name,Survived,Pclass,Name,Survived,Pclass
0,"Braund, Mr. Owen Harris",0.0,3.0,aditya,aditya,aditya
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1.0,1.0,aditya,aditya,aditya
2,"Heikkinen, Miss. Laina",1.0,3.0,aditya,aditya,aditya
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1.0,1.0,aditya,aditya,aditya
4,"Allen, Mr. William Henry",0.0,3.0,aditya,aditya,aditya
5,aditya,aditya,aditya,"Moran, Mr. James",0.0,3.0
6,aditya,aditya,aditya,"McCarthy, Mr. Timothy J",0.0,1.0
7,aditya,aditya,aditya,"Palsson, Master. Gosta Leonard",0.0,3.0
8,aditya,aditya,aditya,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1.0,3.0
9,aditya,aditya,aditya,"Nasser, Mrs. Nicholas (Adele Achem)",1.0,2.0

In [ ]:
data1=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[5,6,7,8,9],
    'c':[56,78,65,43,21]
})

In [ ]:
data2=pd.DataFrame({
    'A':[7,8,9,5,4],
    'D':[6,5,4,3,2],
    'C':[78,43,54,6,8]
})

#merge

In [ ]:
pd.merge(data1,data2)

   A  B   c  D  C
0  4  8  43  2  8
1  5  9  21  3  6

In [ ]:
data1

   A  B   c
0  1  5  56
1  2  6  78
2  3  7  65
3  4  8  43
4  5  9  21

In [ ]:
data2

   A  D   C
0  7  6  78
1  8  5  43
2  9  4  54
3  5  3   6
4  4  2   8

#merge operation joins
these are basically based on the sql joins.

In [ ]:
pd.merge(data1,data2,how='left')

   A  B   c    D    C
0  1  5  56  NaN  NaN
1  2  6  78  NaN  NaN
2  3  7  65  NaN  NaN
3  4  8  43  2.0  8.0
4  5  9  21  3.0  6.0

In [ ]:
pd.merge(data1,data2,how='right')

   A    B     c  D   C
0  7  NaN   NaN  6  78
1  8  NaN   NaN  5  43
2  9  NaN   NaN  4  54
3  5  9.0  21.0  3   6
4  4  8.0  43.0  2   8

In [ ]:
pd.merge(data1,data2,how='outer')

   A    B     c    D     C
0  1  5.0  56.0  NaN   NaN
1  2  6.0  78.0  NaN   NaN
2  3  7.0  65.0  NaN   NaN
3  4  8.0  43.0  2.0   8.0
4  5  9.0  21.0  3.0   6.0
5  7  NaN   NaN  6.0  78.0
6  8  NaN   NaN  5.0  43.0
7  9  NaN   NaN  4.0  54.0

In [ ]:
data1=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[5,6,7,8,9],
    'c':[56,78,65,43,21]},
    index=['a','b','c','d','e']
)

In [ ]:
data2=pd.DataFrame({
    'AA':[7,8,9,5,4],
    'D':[6,5,4,3,2],
    'C':[78,43,54,6,8]
},index=['a','b','g','h','i'])

In [ ]:
data1

   A  B   c
a  1  5  56
b  2  6  78
c  3  7  65
d  4  8  43
e  5  9  21

In [ ]:
data2

   A  D   C
a  7  6  78
b  8  5  43
g  9  4  54
h  5  3   6
i  4  2   8

In [ ]:
data1.join(data2)

   A  B   c   AA    D     C
a  1  5  56  7.0  6.0  78.0
b  2  6  78  8.0  5.0  43.0
c  3  7  65  NaN  NaN   NaN
d  4  8  43  NaN  NaN   NaN
e  5  9  21  NaN  NaN   NaN

In [ ]:
adi

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500

#Apply function in Pandas

In [ ]:
#we are going to use apply function
adi['Fare_INR']=adi['Fare'].apply(lambda x:x*82)

/tmp/ipython-input-178-1889099038.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adi['Fare_INR']=adi['Fare'].apply(lambda x:x*82)

In [ ]:
adi

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Fare_INR
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,594.5000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,5845.2306
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,649.8500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,4354.2000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,660.1000
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,1066.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,2460.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,1922.9000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,2460.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,635.5000

In [ ]:
adi.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Fare_INR
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,594.5000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,5845.2306
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,649.8500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,4354.2000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,660.1000

In [ ]:
adi['len_name']=adi['Name'].apply(lambda x:len(x))

/tmp/ipython-input-181-777354525.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adi['len_name']=adi['Name'].apply(lambda x:len(x))

In [ ]:
adi['len_name'].head()

0    23
1    51
2    22
3    44
4    24
Name: len_name, dtype: int64

In [ ]:
def cat_fare(x):
  if x<10:
    return 'cheap'
  elif x>=10 and x<20:
    return 'mid'

  else:
    return 'high'

In [ ]:
adi['cat_fare']=adi['Fare'].apply(cat_fare)

/tmp/ipython-input-187-3305788543.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adi['cat_fare']=adi['Fare'].apply(cat_fare)

In [ ]:
adi

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Fare_INR,len_name,cat_fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,594.5000,23,cheap
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,5845.2306,51,high
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,649.8500,22,cheap
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,4354.2000,44,high
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,660.1000,24,cheap
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,1066.0000,21,mid
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,2460.0000,28,high
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,1922.9000,40,high
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,2460.0000,21,high
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,635.5000,19,cheap